### ISSUE TITLE
Portscanning error

### ISSUE THREAD

**Issue by ghost** [capt-meelo/LazyRecon#1]
Great tool..

But i keep getting error on port scanning. Says the html is generated but nothing is.

**Comment by capt-meelo** [comment]
Please share the console output?

**Comment by ghost** [comment]
![nmap](https://user-images.githubusercontent.com/47085224/53477173-2ce86580-3a85-11e9-800b-fa73a15d6928.png)

That is the result of the ouput.

![nmap2](https://user-images.githubusercontent.com/47085224/53477439-c152c800-3a85-11e9-85f4-87acec552253.png)

That is the output in the portscan folder.

The problems do come when trying to save the nmap output. I tried finding a solution, however i ended up piping the output to a file.

**Comment by capt-meelo** [comment]
Thanks for sending the STDOUT. The reason you're getting that error is because the `masscan.xml` file is empty. Since it's empty, nmap will produce empty result too. 

Are you running this on a VPS or on your local machine? If you're running this on your local machine, you have to reduce masscan's `--rate` option.

**Comment by ghost** [comment]
I was running on a vps on digital ocean. What is the recommended rate for masscan? I normally put 1 million,,,😎

**Comment by capt-meelo** [comment]
Based on exp, 100k should be good. Greater than that causes masscan to miss some open ports especially when scanning large port ranges.

**Comment by ghost** [comment]
Cool thanks...
